pipeline:
  identifier: Build_cicd_pipeline_train_schedule_canary_1692770754522
  name: Build cicd-pipeline-train-schedule-canary
  orgIdentifier: default
  projectIdentifier: first_demo
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1692693721382
        repoName: sharath-c7/cicd-pipeline-train-schedule-canary
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: npminstall
                  name: npm_install
                  spec:
                    command: npm install
                  timeout: ""
                  type: Run
              - step:
                  identifier: npmtest
                  name: npm_test
                  spec:
                    command: npm run test
                  timeout: ""
                  type: Run
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    image: plugins/docker
                    settings:
                      dry_run: "true"
                      repo: hello/world
                      tags: latest
                  timeout: ""
                  type: Plugin
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
